### ISSUE TITLE
Distorted sulfonamide geometries in 2.1.0-rc.1

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-forcefields#64]
@j-wags Hi Jeff Thank you for the help.
I have retested this with the new 2.1.0 but I don't think this has been fixed yet? Thank you.
![image](https://user-images.githubusercontent.com/6242032/233431770-07743e48-2871-459f-a7dd-33168d4ea44f.png)

_Originally posted by @xiki-tempula in https://github.com/openforcefield/openff-toolkit/issues/1522#issuecomment-1516634852_

**Comment by pavankum** [comment]
@j-wags I can take a look.

**Comment by xiki-tempula** [comment]
Thank you.

**Comment by jaketanderson** [comment]
@mattwthompson using your code with `openff-2.2.0.offxml` gives me a much nicer minimized structure.

![image](https://github.com/user-attachments/assets/7a6a0247-ca73-416f-9788-e6797abac0f5)

**Comment by amcisaac** [comment]
The origin of the issue was that the k's for the sulfamide angles (a31 and a32) were optimizing to a very low value during force field optimization. We think this low k led to the angle term being overwhelmed by nonbonded interactions (just a hypothesis). We’ve temporarily fixed it in Sage 2.2 by very heavily regularizing (all) the parameters during optimization, preventing them from deviating too much from the initial modified seminario method value, but that’s not a permanent solution as the regularization did cause some minor issues with other parameters. We're looking into more lasting ways to fix it for future releases, but from the user side, this should be fixed now.
